/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedSquadsRouteImport } from './routes/_authenticated.squads'
import { Route as AuthenticatedStructureRouteImport } from './routes/_authenticated.structure'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as EmBreveIndexRouteImport } from './routes/em-breve/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated.clients.$clientId'
import { Route as AuthenticatedClientsChurnRouteImport } from './routes/_authenticated.clients.churn'
import { Route as AuthenticatedClientsContractsRouteImport } from './routes/_authenticated.clients.contracts'
import { Route as AuthenticatedClientsManageRouteImport } from './routes/_authenticated.clients.manage'
import { Route as AuthenticatedComercialCrmRouteImport } from './routes/_authenticated.comercial.crm'
import { Route as AuthenticatedFinancasIndexRouteImport } from './routes/_authenticated.financas.index'
import { Route as AuthenticatedProjectsContentApprovalRouteImport } from './routes/_authenticated.projects.content-approval'
import { Route as AuthenticatedProjectsDeliverablesRouteImport } from './routes/_authenticated.projects.deliverables'
import { Route as AuthenticatedProjectsTasksRouteImport } from './routes/_authenticated.projects.tasks'
import { Route as PublicApprovalTokenRouteImport } from './routes/public.approval.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSquadsRoute = AuthenticatedSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStructureRoute = AuthenticatedStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveIndexRoute = EmBreveIndexRouteImport.update({
  id: '/em-breve/',
  path: '/em-breve/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsChurnRoute =
  AuthenticatedClientsChurnRouteImport.update({
    id: '/clients/churn',
    path: '/clients/churn',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsContractsRoute =
  AuthenticatedClientsContractsRouteImport.update({
    id: '/clients/contracts',
    path: '/clients/contracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsManageRoute =
  AuthenticatedClientsManageRouteImport.update({
    id: '/clients/manage',
    path: '/clients/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialCrmRoute =
  AuthenticatedComercialCrmRouteImport.update({
    id: '/comercial/crm',
    path: '/comercial/crm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancasIndexRoute =
  AuthenticatedFinancasIndexRouteImport.update({
    id: '/financas/',
    path: '/financas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsContentApprovalRoute =
  AuthenticatedProjectsContentApprovalRouteImport.update({
    id: '/content-approval',
    path: '/content-approval',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsDeliverablesRoute =
  AuthenticatedProjectsDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsTasksRoute =
  AuthenticatedProjectsTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const PublicApprovalTokenRoute = PublicApprovalTokenRouteImport.update({
  id: '/public/approval/$token',
  path: '/public/approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/squads': typeof AuthenticatedSquadsRoute
  '/structure': typeof AuthenticatedStructureRoute
  '/users': typeof AuthenticatedUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/em-breve/': typeof EmBreveIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/churn': typeof AuthenticatedClientsChurnRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsRoute
  '/clients/manage': typeof AuthenticatedClientsManageRoute
  '/comercial/crm': typeof AuthenticatedComercialCrmRoute
  '/projects/content-approval': typeof AuthenticatedProjectsContentApprovalRoute
  '/projects/deliverables': typeof AuthenticatedProjectsDeliverablesRoute
  '/projects/tasks': typeof AuthenticatedProjectsTasksRoute
  '/public/approval/$token': typeof PublicApprovalTokenRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/financas/': typeof AuthenticatedFinancasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/squads': typeof AuthenticatedSquadsRoute
  '/structure': typeof AuthenticatedStructureRoute
  '/users': typeof AuthenticatedUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/em-breve': typeof EmBreveIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/churn': typeof AuthenticatedClientsChurnRoute
  '/clients/contracts': typeof AuthenticatedClientsContractsRoute
  '/clients/manage': typeof AuthenticatedClientsManageRoute
  '/comercial/crm': typeof AuthenticatedComercialCrmRoute
  '/projects/content-approval': typeof AuthenticatedProjectsContentApprovalRoute
  '/projects/deliverables': typeof AuthenticatedProjectsDeliverablesRoute
  '/projects/tasks': typeof AuthenticatedProjectsTasksRoute
  '/public/approval/$token': typeof PublicApprovalTokenRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/financas': typeof AuthenticatedFinancasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/squads': typeof AuthenticatedSquadsRoute
  '/_authenticated/structure': typeof AuthenticatedStructureRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/em-breve/': typeof EmBreveIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/churn': typeof AuthenticatedClientsChurnRoute
  '/_authenticated/clients/contracts': typeof AuthenticatedClientsContractsRoute
  '/_authenticated/clients/manage': typeof AuthenticatedClientsManageRoute
  '/_authenticated/comercial/crm': typeof AuthenticatedComercialCrmRoute
  '/_authenticated/projects/content-approval': typeof AuthenticatedProjectsContentApprovalRoute
  '/_authenticated/projects/deliverables': typeof AuthenticatedProjectsDeliverablesRoute
  '/_authenticated/projects/tasks': typeof AuthenticatedProjectsTasksRoute
  '/public/approval/$token': typeof PublicApprovalTokenRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/financas/': typeof AuthenticatedFinancasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/squads'
    | '/structure'
    | '/users'
    | '/auth/login'
    | '/em-breve/'
    | '/clients/$clientId'
    | '/clients/churn'
    | '/clients/contracts'
    | '/clients/manage'
    | '/comercial/crm'
    | '/projects/content-approval'
    | '/projects/deliverables'
    | '/projects/tasks'
    | '/public/approval/$token'
    | '/clients/'
    | '/financas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/squads'
    | '/structure'
    | '/users'
    | '/auth/login'
    | '/em-breve'
    | '/clients/$clientId'
    | '/clients/churn'
    | '/clients/contracts'
    | '/clients/manage'
    | '/comercial/crm'
    | '/projects/content-approval'
    | '/projects/deliverables'
    | '/projects/tasks'
    | '/public/approval/$token'
    | '/clients'
    | '/financas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/squads'
    | '/_authenticated/structure'
    | '/_authenticated/users'
    | '/auth/login'
    | '/em-breve/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/churn'
    | '/_authenticated/clients/contracts'
    | '/_authenticated/clients/manage'
    | '/_authenticated/comercial/crm'
    | '/_authenticated/projects/content-approval'
    | '/_authenticated/projects/deliverables'
    | '/_authenticated/projects/tasks'
    | '/public/approval/$token'
    | '/_authenticated/clients/'
    | '/_authenticated/financas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  EmBreveIndexRoute: typeof EmBreveIndexRoute
  PublicApprovalTokenRoute: typeof PublicApprovalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/squads': {
      id: '/_authenticated/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof AuthenticatedSquadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/structure': {
      id: '/_authenticated/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof AuthenticatedStructureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve/': {
      id: '/em-breve/'
      path: '/em-breve'
      fullPath: '/em-breve/'
      preLoaderRoute: typeof EmBreveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/churn': {
      id: '/_authenticated/clients/churn'
      path: '/clients/churn'
      fullPath: '/clients/churn'
      preLoaderRoute: typeof AuthenticatedClientsChurnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/contracts': {
      id: '/_authenticated/clients/contracts'
      path: '/clients/contracts'
      fullPath: '/clients/contracts'
      preLoaderRoute: typeof AuthenticatedClientsContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/manage': {
      id: '/_authenticated/clients/manage'
      path: '/clients/manage'
      fullPath: '/clients/manage'
      preLoaderRoute: typeof AuthenticatedClientsManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/crm': {
      id: '/_authenticated/comercial/crm'
      path: '/comercial/crm'
      fullPath: '/comercial/crm'
      preLoaderRoute: typeof AuthenticatedComercialCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financas/': {
      id: '/_authenticated/financas/'
      path: '/financas'
      fullPath: '/financas/'
      preLoaderRoute: typeof AuthenticatedFinancasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/content-approval': {
      id: '/_authenticated/projects/content-approval'
      path: '/content-approval'
      fullPath: '/projects/content-approval'
      preLoaderRoute: typeof AuthenticatedProjectsContentApprovalRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/deliverables': {
      id: '/_authenticated/projects/deliverables'
      path: '/deliverables'
      fullPath: '/projects/deliverables'
      preLoaderRoute: typeof AuthenticatedProjectsDeliverablesRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/tasks': {
      id: '/_authenticated/projects/tasks'
      path: '/tasks'
      fullPath: '/projects/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/public/approval/$token': {
      id: '/public/approval/$token'
      path: '/public/approval/$token'
      fullPath: '/public/approval/$token'
      preLoaderRoute: typeof PublicApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsContentApprovalRoute: typeof AuthenticatedProjectsContentApprovalRoute
  AuthenticatedProjectsDeliverablesRoute: typeof AuthenticatedProjectsDeliverablesRoute
  AuthenticatedProjectsTasksRoute: typeof AuthenticatedProjectsTasksRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsContentApprovalRoute:
    AuthenticatedProjectsContentApprovalRoute,
  AuthenticatedProjectsDeliverablesRoute:
    AuthenticatedProjectsDeliverablesRoute,
  AuthenticatedProjectsTasksRoute: AuthenticatedProjectsTasksRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSquadsRoute: typeof AuthenticatedSquadsRoute
  AuthenticatedStructureRoute: typeof AuthenticatedStructureRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsChurnRoute: typeof AuthenticatedClientsChurnRoute
  AuthenticatedClientsContractsRoute: typeof AuthenticatedClientsContractsRoute
  AuthenticatedClientsManageRoute: typeof AuthenticatedClientsManageRoute
  AuthenticatedComercialCrmRoute: typeof AuthenticatedComercialCrmRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedFinancasIndexRoute: typeof AuthenticatedFinancasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSquadsRoute: AuthenticatedSquadsRoute,
  AuthenticatedStructureRoute: AuthenticatedStructureRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsChurnRoute: AuthenticatedClientsChurnRoute,
  AuthenticatedClientsContractsRoute: AuthenticatedClientsContractsRoute,
  AuthenticatedClientsManageRoute: AuthenticatedClientsManageRoute,
  AuthenticatedComercialCrmRoute: AuthenticatedComercialCrmRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedFinancasIndexRoute: AuthenticatedFinancasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  EmBreveIndexRoute: EmBreveIndexRoute,
  PublicApprovalTokenRoute: PublicApprovalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
